### ISSUE TITLE
🙋 ID-request

### ISSUE THREAD

**Issue by HendrikBorgelt** [nfdi4cat/voc4cat#39]
### Your ORCID identifier.

https://orcid.org/0000-0001-5886-7860

### The ROR of the organization you work for.

https://ror.org/01k97gp34

### Number of IDs requested.

100

### Additional information.

I would like to have 100 Numbers for ID's to extend the Vocabulary. If We already have a Method for generating ID's for Ontologies I would also be interested in getting ID's for working on Ontology terms.

**Comment by dalito** [comment]
Hi Hendrik! #40 reserves 7101...7200 for you.

Regarding IDs for an Ontology: In order to use w3id.org redirects, we need to have the ontology contents hosted somewhere (preferably NFDI4Cat GitHub pages). The config from NFDI4Cat is [here in w3id.org repo](https://github.com/perma-id/w3id.org/tree/master/nfdi4cat). We can add new redirects as needed. Writing the redirect rules requires a (permanent) name for the ontology, an ID-scheme and the URLs where the artifacts should be retrieved from. If you have everything in place, I can submit the PR on w3id.org.

I close this issue here because it is out of scope for voc4cat. When you are ready with the preparations, just notify me by email or via an issue in your ontology repo.
